"use client";

import React from 'react';
import Image from 'next/image';
import Link from 'next/link';
import { FiArrowLeft } from 'react-icons/fi';

const DisclaimerPage = () => {
  return (
    <div className="flex flex-col min-h-screen bg-black text-white font-sans antialiased items-center justify-center p-8">
      <div className="max-w-4xl mx-auto bg-white/10 backdrop-blur-md rounded-2xl shadow-lg p-10 border border-white/20">
        <div className="flex justify-center mb-6">
          <Image src="/nexo.png" width={80} height={80} alt="Nexo Logo" className="rounded-full ring-4 ring-white/20" />
        </div>
        <h1 className="text-4xl font-bold text-center mb-6 bg-clip-text text-transparent bg-gradient-to-r from-cyan-400 to-blue-500">Important Disclaimer</h1>
        <div className="text-gray-300 text-lg leading-relaxed space-y-6">
          <p>
            Please be advised that Nexo AI is a functional conversational AI designed to provide assistance,
            operating similarly to other advanced AI chatbots. However, this entire application, including all its content,
            features, and the responses generated by Nexo AI, is developed solely for academic and demonstration purposes
            as part of a school project.
          </p>
          <p>
            The information presented and discussed within this platform, including any specific details, facts, or scenarios,
            is purely fictional and illustrative. It is not intended to convey real-world factual information, provide
            professional advice, or be used for any practical, commercial, or operational purposes. Any resemblance to
            real entities, services, products, or data is entirely coincidental.
          </p>
          <p>
            Users should not rely on any content or interactions with Nexo AI for accuracy, completeness, or suitability
            for any real-world application. This project serves as an educational exercise to explore the capabilities
            and development of AI technologies.
          </p>
        </div>
        <div className="mt-10 text-center">
          <Link href="/" passHref>
            <button className="group flex items-center justify-center bg-gradient-to-r from-cyan-500 to-blue-600 text-white px-7 py-3 rounded-full shadow-lg hover:shadow-cyan-500/50 transition-all transform hover:scale-105">
              <FiArrowLeft className="mr-2 transition-transform group-hover:-translate-x-1" />
              <span className="font-semibold">Return to Homepage</span>
            </button>
          </Link>
        </div>
      </div>
    </div>
  );
};

export default DisclaimerPage;
