"use client";

import React from 'react';
import Image from 'next/image';
import Link from 'next/link';
import { FiArrowLeft } from 'react-icons/fi';
import Button from '@mui/material/Button';

const DisclaimerPage = () => {
  return (
    <div className="flex flex-col min-h-screen bg-black text-white font-sans antialiased items-center justify-center p-8">
      <div className="max-w-4xl mx-auto bg-white/10 backdrop-blur-md rounded-2xl shadow-lg p-10 border border-white/20">
        <div className="flex justify-center mb-6">
          <Image src="/nexo.png" width={80} height={80} alt="Nexo Logo" className="rounded-full ring-4 ring-white/20" />
        </div>
        <h1 className="text-4xl font-bold text-center mb-6 bg-clip-text text-transparent bg-gradient-to-r from-cyan-400 to-blue-500">Important Disclaimer</h1>
        <div className="text-gray-300 text-lg leading-relaxed space-y-6">
          <p>
            Please be advised that Nexo AI is a functional conversational AI designed to provide assistance,
            operating similarly to other advanced AI chatbots. However, this entire application, including all its content,
            features, and the responses generated by Nexo AI, is developed solely for academic and demonstration purposes
            as part of a school project.
          </p>
          <p>
            The information presented and discussed within this platform, including any specific details, facts, or scenarios,
            is purely fictional and illustrative. It is not intended to convey real-world factual information, provide
            professional advice, or be used for any practical, commercial, or operational purposes. Any resemblance to
            real entities, services, products, or data is entirely coincidental.
          </p>
          <p>
            Users should not rely on any content or interactions with Nexo AI for accuracy, completeness, or suitability
            for any real-world application. This project serves as an educational exercise to explore the capabilities
            and development of AI technologies.
          </p>
        </div>
        <div className="mt-10 text-center">
          <Link href="/" passHref>
            <Button
              component="a" // Use 'a' for Next.js Link
              sx={{
                display: 'flex',
                alignItems: 'center',
                justifyContent: 'center',
                background: 'linear-gradient(to right, #06b6d4, #3b82f6)', // from-cyan-500 to-blue-600
                color: 'white',
                padding: '12px 28px', // px-7 py-3
                borderRadius: '9999px', // rounded-full
                boxShadow: '0 10px 15px -3px rgba(0, 0, 0, 0.1), 0 4px 6px -2px rgba(0, 0, 0, 0.05)', // shadow-lg
                transition: 'all 0.2s ease-in-out', // transition-all transform
                '&:hover': {
                  boxShadow: '0 20px 25px -5px rgba(6, 182, 212, 0.5), 0 8px 10px -6px rgba(6, 182, 212, 0.5)', // hover:shadow-cyan-500/50
                  transform: 'scale(1.05)', // hover:scale-105
                },
              }}
            >
              <FiArrowLeft className="mr-2 transition-transform group-hover:-translate-x-1" />
              <span className="font-semibold">Return to Homepage</span>
            </Button>
          </Link>
        </div>
      </div>
    </div>
  );
};

export default DisclaimerPage;
