"use client";

import React from 'react';
import Image from 'next/image';
import Link from 'next/link';
import { FiArrowLeft, FiShield, FiInfo, FiAlertCircle, FiUserCheck } from 'react-icons/fi';
import Button from '@mui/material/Button';
import Typography from '@mui/material/Typography';
import Box from '@mui/material/Box';
import { motion } from 'framer-motion';

const DisclaimerPage = () => {
  const sections = [
    {
      title: "Purpose of Nexo AI",
      icon: <FiInfo className="text-cyan-400 text-2xl" />,
      content: "Please be advised that Nexo AI is a functional conversational AI designed to provide assistance, operating similarly to other advanced AI chatbots. However, this entire application, including all its content, features, and the responses generated by Nexo AI, is developed solely for academic and demonstration purposes as part of a school project."
    },
    {
      title: "Nature of Information",
      icon: <FiAlertCircle className="text-blue-400 text-2xl" />,
      content: "The information presented and discussed within this platform, including any specific details, facts, or scenarios, is purely fictional and illustrative. It is not intended to convey real-world factual information, provide professional advice, or be used for any practical, commercial, or operational purposes."
    },
    {
      title: "User Responsibility",
      icon: <FiUserCheck className="text-indigo-400 text-2xl" />,
      content: "Users should not rely on any content or interactions with Nexo AI for accuracy, completeness, or suitability for any real-world application. This project serves as an educational exercise to explore the capabilities and development of AI technologies."
    }
  ];

  return (
    <div className="relative flex flex-col min-h-screen bg-black text-white font-sans antialiased items-center justify-center p-6 overflow-hidden">
      {/* Background Decorative Elements */}
      <div className="absolute top-0 right-1/4 w-[600px] h-[600px] bg-cyan-600/10 rounded-full blur-[140px] pointer-events-none"></div>
      <div className="absolute bottom-0 left-1/4 w-[600px] h-[600px] bg-blue-600/10 rounded-full blur-[140px] pointer-events-none"></div>

      <motion.div 
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.6 }}
        className="relative z-10 max-w-3xl w-full bg-white/5 backdrop-blur-2xl rounded-[40px] shadow-2xl p-8 md:p-14 border border-white/10"
      >
        <div className="flex flex-col items-center mb-10">
          <div className="relative w-24 h-24 mb-6">
            <div className="absolute inset-0 bg-blue-500/30 rounded-full blur-2xl"></div>
            <Image src="/nexo.png" layout="fill" objectFit="contain" alt="Nexo Logo" className="relative rounded-full ring-2 ring-white/20 p-1" />
          </div>
          <div className="flex items-center gap-3 mb-2">
            <FiShield className="text-blue-400 text-2xl" />
            <h1 className="text-3xl md:text-5xl font-black tracking-tight text-white">Legal Notice</h1>
          </div>
          <div className="h-1 w-20 bg-gradient-to-r from-cyan-400 to-blue-600 rounded-full"></div>
        </div>
        
        <div className="space-y-6">
          {sections.map((section, index) => (
            <motion.div
              key={index}
              initial={{ opacity: 0, x: -20 }}
              animate={{ opacity: 1, x: 0 }}
              transition={{ delay: 0.1 * (index + 1) }}
              className="group p-6 rounded-[28px] bg-white/5 border border-white/10 hover:bg-white/10 hover:border-white/20 transition-all duration-300"
            >
              <div className="flex items-center gap-4 mb-3">
                <div className="p-2 rounded-xl bg-white/5 group-hover:scale-110 transition-transform duration-300">
                  {section.icon}
                </div>
                <h3 className="text-xl font-bold text-white tracking-tight">{section.title}</h3>
              </div>
              <p className="text-gray-400 leading-relaxed text-[1.05rem]">
                {section.content}
              </p>
            </motion.div>
          ))}
        </div>

        <div className="mt-12 flex flex-col items-center">
          <Link href="/" passHref>
            <Button
              sx={{
                background: 'linear-gradient(to right, #06b6d4, #3b82f6)',
                color: 'white',
                px: 6,
                py: 2,
                borderRadius: '50px',
                fontWeight: 'bold',
                textTransform: 'none',
                fontSize: '1rem',
                boxShadow: '0 10px 30px -10px rgba(6, 182, 212, 0.5)',
                transition: 'all 0.3s ease',
                '&:hover': {
                  boxShadow: '0 15px 35px -10px rgba(6, 182, 212, 0.7)',
                  transform: 'translateY(-2px)',
                },
              }}
            >
              <FiArrowLeft className="mr-2" />
              Return Home
            </Button>
          </Link>
          <p className="mt-6 text-gray-500 text-sm">Last updated: February 2026</p>
        </div>
      </motion.div>
    </div>
  );
};

export default DisclaimerPage;
